### ISSUE TITLE
run issue

### ISSUE THREAD

**Issue by zleeeeee** [IhabMohamed/log-MPPI_ros#2]
When I run `roslaunch jackal_gazebo world_stage.launch env_name:="forest0"` and `roslaunch mppi_control control_stage.launch normal_dist:=true`, it happens the following error. Is it related to jackal_ros?
![2024-08-27 22-14-54屏幕截图](https://github.com/user-attachments/assets/3f069346-fd7d-4143-ae5d-1ff9cd9a4656)

**Comment by IhabMohamed** [comment]
Hi @zleeeeee,

Thank you so much for your interest in our work, and I apologize for the delayed response. I'm glad to hear that you were able to resolve the issue. 

Wishing you all the best!
